### ISSUE TITLE
Significant changes have taken place in the creation of front-end time accounts.  Can someone renew this module?

### ISSUE THREAD

**Issue by GoMateoGo** [azerothcore/Registration-Page#1]
Significant changes have taken place in the creation of front-end time accounts.

Can someone renew this module?

I see that the latest calculateverifier first capitalizes the result of SHA1's account and password, and then performs SHA1 again with salt. I don't know how to write the database. I can't convert it correctly through cast (salt, char) in SQL.

**Comment by nolt** [comment]
Hi @hahalmtdhl 

Yes I know about salt changes, I will fix it ASAP.

**Comment by nolt** [comment]
Registrations has been fixed.
